"""add table

Revision ID: 86f0b9380e68
Revises: 581f8b78f6a9
Create Date: 2025-06-15 00:15:27.615307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f0b9380e68'
down_revision: Union[str, None] = '581f8b78f6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practices',
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('practice_text', sa.String(length=500), nullable=False),
    sa.Column('practice_type', sa.Enum('PHONEME', 'WORD', 'SENTENCE', 'FREE', name='writingtype'), nullable=False),
    sa.Column('practice__character', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('practice_id')
    )
    op.create_index(op.f('ix_practices_practice_id'), 'practices', ['practice_id'], unique=False)
    op.create_table('steps',
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('step_mission', sa.String(length=500), nullable=False),
    sa.Column('step_type', sa.Enum('PHONEME', 'WORD', 'SENTENCE', 'FREE', name='writingtype'), nullable=False),
    sa.Column('step_charcter', sa.String(length=10), nullable=False),
    sa.Column('step_text', sa.String(length=500), nullable=False),
    sa.Column('step_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index(op.f('ix_steps_step_id'), 'steps', ['step_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'KAKAO', 'NAVER', 'APPLE', name='authprovider'),  nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('profile_pic', sa.String(length=500), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('mission_records',
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('isCleared', sa.Boolean(), nullable=False),
    sa.Column('clear_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['steps.step_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mission_id')
    )
    op.create_index(op.f('ix_mission_records_mission_id'), 'mission_records', ['mission_id'], unique=False)
    op.create_table('practice_records',
    sa.Column('practiceRecord_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('practice_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.practice_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('practiceRecord_id')
    )
    op.create_index(op.f('ix_practice_records_practiceRecord_id'), 'practice_records', ['practiceRecord_id'], unique=False)
    op.create_table('results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['mission_records.mission_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_results_result_id'), 'results', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_result_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_practice_records_practiceRecord_id'), table_name='practice_records')
    op.drop_table('practice_records')
    op.drop_index(op.f('ix_mission_records_mission_id'), table_name='mission_records')
    op.drop_table('mission_records')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_steps_step_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_practices_practice_id'), table_name='practices')
    op.drop_table('practices')
    # ### end Alembic commands ###
