"""clear_time에서 submission_time으로 변경

Revision ID: dad42e64cdf0
Revises: cb4776b2c2fb
Create Date: 2025-10-26 21:47:06.993674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dad42e64cdf0'
down_revision: Union[str, None] = 'cb4776b2c2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_records', sa.Column('submission_time', sa.DateTime(), nullable=True))
    op.drop_column('mission_records', 'clear_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_records', sa.Column('clear_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('mission_records', 'submission_time')
    # ### end Alembic commands ###
