"""Add user_type to User and step_tip to Step

Revision ID: e6997e6c27ff
Revises: e7bc311027e6
Create Date: 2025-11-05 20:54:39.244106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6997e6c27ff'
down_revision: Union[str, None] = 'e7bc311027e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_type=sa.Enum('CHILD', 'ADULT', 'FOREIGN', name='usertype')
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_type.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('user_type', sa.Enum('CHILD', 'ADULT', 'FOREIGN', name='usertype'), server_default='CHILD', nullable=True))
    op.alter_column('steps', 'step_tip',
               existing_type=sa.String(length=500),
               server_default='천천히 왼쪽, 오른쪽, 위, 아래 간격을 맞추면서 적어봐요',
               nullable=True)
    op.execute("""
        INSERT INTO steps (step_mission, step_type, step_character, step_text, step_time, step_tip)
        VALUES 
            ('밑의 단어를 정확히 써보자', 'WORD', 'assets/character/rabbitTeacher.png', '비행기', 120, '받침 있는 글자에 주의해서 천천히 써보아요'),
            ('밑의 단어를 정확히 써보자', 'WORD', 'assets/character/rabbitTeacher.png', '아름다움', 120, 'ㄹ에 주의해서 천천히 써보아요');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM steps WHERE step_text IN ('비행기', '아름다움');
    """)
    op.alter_column('steps', 'step_tip',
               existing_type=sa.String(length=500),
               server_default=None,
               nullable=True)
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
