"""tip attribute add

Revision ID: e7bc311027e6
Revises: dad42e64cdf0
Create Date: 2025-10-27 00:05:23.238561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7bc311027e6'
down_revision: Union[str, None] = 'dad42e64cdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practices', sa.Column('practice_tip', sa.String(length=500), nullable=True))
    op.add_column('steps', sa.Column('step_tip', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'step_tip')
    op.drop_column('practices', 'practice_tip')
    # ### end Alembic commands ###
