"""fix tip attribute

Revision ID: fad2ae4a369a
Revises: e6997e6c27ff
Create Date: 2025-11-06 00:37:50.011121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad2ae4a369a'
down_revision: Union[str, None] = 'e6997e6c27ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE steps 
        SET step_tip = '천천히 왼쪽, 오른쪽, 위, 아래 간격을 맞추면서 적어봐요' 
        WHERE step_tip IS NULL;
    """)
    op.execute("""
        UPDATE practices
        SET practice_tip = '천천히 왼쪽, 오른쪽, 위, 아래 간격을 맞추면서 적어봐요' 
        WHERE practice_tip IS NULL;
    """)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
